package com.sammydj.etsytool.model.listing

data class Listing(
    val listingId: Long?,
    val state: String?,
    val userId: Int?,
    val categoryId: Int?,
    val title: String?,
    val description: String?,
    val creationTsz: Float?,
    val endingTsz: Float?,
    val originalCreationTsz: Float?,
    val lastModifiedTsz: Float?,
    val price: String?,
    val currencyCode: String?,
    val quantity: Int?,
    val tags: List<String>?,
    val taxonomyId: Int?,
    val materials: List<String>?,
    val shopSectionId: Int?,
    val url: String?,
    val views: Int?,
    val numFavorers: Int?,
    val processingMin: Int?,
    val processingMax: Int?,
    val itemWeight: Int?,
    val itemWeightUnit: ItemWeightUnit?,
    val itemLength: Int?,
    val itemWidth: Int?,
    val itemHeight: Int?,
    val itemDimensionsUnit: ItemDimensionsUnit?,
    val style: List<String>?,
    val nonTaxable: Boolean?,
    val isCustomizable: Boolean?,
    val isDigital: Boolean?,
    val fileData: String?,
    val hasVariations: Boolean?
)
